---
collections:

- name: ansible.posix
  version: 1.1.1

- name: community.general
  version: 3.0.0

roles:

- src: dev-sec.ssh-hardening
  version: "6.1.3"

- src: nvidia.nvidia_docker
  version: "v1.2.1"