
# NTP configuration
# Playbook: chrony-client
chrony_install: yes
chrony_service_state: "started"
chrony_service_enabled: "yes"
chrony_timezone: "Etc/UTC"
chrony_config_server:
  - 0.pool.ntp.org
  - 1.pool.ntp.org
  - 2.pool.ntp.org
  - 3.pool.ntp.org

# Set hostname based on inventory file
set_hostname: true

################################################################################
# NVIDIA                                                                       #
################################################################################
# NVIDIA GPU configuration
# Playbook: nvidia-cuda
cuda_version: cuda-toolkit-11-3

# Debugging var: force install NVIDIA driver even if GPU not detected
nvidia_driver_force_install: false


################################################################################
# CONTAINER RUNTIME                                                            #
################################################################################
# Docker configuration
# Playbook: docker, nvidia-docker
#
docker_install: yes
docker_version: '19.03'
docker_dns_servers_strict: no
docker_storage_options: -s overlay2
# Enable docker iptables
# If this isn't set, containers won't have access to the outside net
# See https://github.com/kubernetes-sigs/kubespray/issues/2002
docker_iptables_enabled: true


# mlops specific config
mlops_dir: /opt/mlops
# Directory for python virtualenv
mlops_venv: '{{ mlops_dir }}/venv'