---
- hosts: gpus
  name: Building docker images
  become: true
  ignore_errors: true
  tags:
    - docker
  tasks:
    - name: update submodules
      ansible.builtin.command: git submodule update --init
    - name: running docker compose
      args:
        chdir: "{{ playbook_dir | dirname | dirname }}/submodules/kubeflow-servers"
      ansible.builtin.command: docker-compose docker-compose.yaml build --parallel
