---
- hosts: gpus
  name: Building docker images
  become: true
  ignore_errors: true
  tags:
    - docker
  tasks:
    - name: update submodules
      ansible.builtin.command: git clone https://github.com/tuttlebr/kubeflow-servers.git /kubeflow-servers
    - name: running docker compose
      args:
        chdir: /kubeflow-servers
      ansible.builtin.command: docker-compose build --parallel
    - name: check builds
      ansible.builtin.command: docker images
