---
- hosts: gpus
  name: Building docker images
  become: true
  ignore_errors: true
  tags:
    - docker
  tasks:
    - name: update MLEs
      ansible.builtin.command: git clone https://github.com/NVIDIA/DeepLearningExamples.git /home/brandon/DeepLearningExamples
    - name: running docker compose
      args:
        chdir: "{{ playbook_dir }}"
      ansible.builtin.command: docker-compose pull
