---
- hosts: gpus
  name: Building docker images
  become: true
  ignore_errors: true
  tags:
    - docker
  tasks:
    - name: update MLEs
      ansible.builtin.git:
        repo: https://github.com/NVIDIA/DeepLearningExamples.git
        dest: /home/brandon/DeepLearningExamples
    - name: copy docker compose file
      ansible.builtin.copy:
        src: docker-compose.yaml
        dest: /home/brandon/docker-compose.yaml
    - name: running docker compose
      ansible.builtin.command: docker-compose --file /home/brandon/docker-compose.yaml pull
