---
- hosts: "{{ hostlist | default('all') }}"
  become: true
  tags:
  - nvidia
  - nvidia_docker
  tasks:
    - name: install custom facts module
      include_role:
        name: facts

    - name: remove docker overrides, specifically to deal with conflicting options from DGX OS
      file:
        path: /etc/systemd/system/docker.service.d/docker-override.conf
        state: absent

    - name: install nvidia-docker
      include_role:
        name: nvidia.nvidia_docker
      when:
        - ansible_local['gpus']['count']
