---
- include: bootstrap/bootstrap-apt.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-python.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-ssh.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-sudo.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-disable-swap.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-docker.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-nvidia.yml
  tags:
    - bootstrap

- include: base-images/data-science.yml
  tags:
    - docker-compose