---
- include: bootstrap/bootstrap-apt.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-python.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-ssh.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-sudo.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-disable-swap.yml
  tags:
    - bootstrap

- include: bootstrap/bootstrap-docker.yml
  when: 
    - docker not in ansible_facts.packages
  tags:
    - bootstrap

- include: bootstrap/bootstrap-nvidia.yml
  when: 
    - nvidia-smi not in ansible_facts.packages
  tags:
    - bootstrap
